### ISSUE TITLE
Window context menu is not clickable

### ISSUE THREAD

**Issue by Saderius** [sentialx/multrin#66] opened 2019-08-08 22:21 UTC
**Bug description**
As in topic.

**To Reproduce**
When you left-click on open app and them right-click on top Multrin bar menu will show up, but you cannot click any option here and when you click around to hide it, will stay.

**Expected behavior**
Clickable options, menu hides when clicked somewhere else.

**Screenshots**
There's a link in image to gif.
[![](https://i.imgur.com/lkXczW5.jpg)](https://i.imgur.com/viTR8LK.gif)

**Details:**
 - Operating System: **Windows 10 Pro, Version 10.0.18362 Build 18362**
 - Multrin version: **latest (downloaded today)**
 - Last known working Multrin version: **none**

**Comment by sentialx** [comment] 2019-08-08 22:42
Duplicate of #12

**Closed by sentialx** 2019-08-08 22:42 UTC
Labels: bug, duplicate
