### ISSUE TITLE
Dragged windows from other Win 10 virtual desktops should not be captured

### ISSUE THREAD

**Issue by orthoceros** [sentialx/multrin#83] opened 2019-09-12 09:53 UTC
**Bug description**
Multrin captures windows from other Win 10 virtual desktops where no Multrin window is open.

**To Reproduce**
Open Multrin in one Win 10 virtual desktop. (I attached an Explorer window and two Excel windows as tabs to it.) Go to another Win 10 virtual desktop (via keyboard hotkey). Drag a window there over the (here invisible) area the Multrin window occupies in the first virtual desktop.

**Expected behavior**
Let me drag windows as usual in Win 10 virtual desktops without an opened Multrin window. Do not capture and move them into the Multrin window on the other virtual desktop.

**Details:**
 - Operating System: Win 10 1809
 - Multrin version: 1.0.0.0
 - Last known working Multrin version: n/a (just tested 1.0.0.0)

**Additional context**
Maybe, Multrin could be made aware, on which virtual desktops its own window is located and then only react to dragged windows on this virtual desktop?

PS: Thanks for this program; I think it could become one of my productivity favorites!

**Comment by sentialx** [comment] 2019-10-07 18:59
Duplicate of #30

**Closed by sentialx** 2019-10-07 18:59 UTC
Labels: duplicate
