### ISSUE TITLE
Multrin tab stays after releasing into own window

### ISSUE THREAD

**Issue by DaKie206** [sentialx/multrin#94] opened 2019-12-15 21:47 UTC
**Bug description**
The `multrin` tab sometimes stays after dragging the window out of `multrin`.

**To Reproduce**
Drag tab out of `multrin`. Doesn't work always.

**Expected behaviour**
Deleting tab after releasing window

**Screenshots**

![image](https://user-images.githubusercontent.com/50425705/70869805-bae9fa00-1f8c-11ea-9e46-3e94be141d14.png)

**Details:**
 - Operating System: Windows 10 Home 1909
 - Multrin version: 1.1.1
 - Last known working Multrin version: ?
 - Scaling (in percentage, if present): 125%

**Additional context**

**Comment by sentialx** [comment] 2019-12-15 21:52
@DaKie206 I can't reproduce... The tab is always closing.

**Comment by sentialx** [comment] 2019-12-15 21:57
Okay I can see it now. It happens when you drag out the window out of Multrin and then drag it back in and release your left mouse button.

**Closed** 2019-12-15 22:21 UTC
Labels: bug
